version: "3.1"
services:
    webserver:
      image: nginx:alpine
      container_name: lnmp-webserver
      working_dir: ${DOCKER_APP_PATH}
      links:
        - "php-fpm"
      volumes:
          - ${APP_PATH}:${DOCKER_APP_PATH}
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "${NGINX_PORT}:80"

    php-fpm:
      build: php-fpm
      container_name: lnmp-php-fpm
      working_dir: ${DOCKER_APP_PATH}
      links:
        - "mysql"
        - "redis"
      volumes:
        - ${APP_PATH}:${DOCKER_APP_PATH}
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    redis:
      image: redis:alpine
      container_name: lnmp-redis

    mysql:
      image: mysql:5.7
      container_name: lnmp-mysql
      working_dir: ${DOCKER_APP_PATH}
      volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/conf:/etc/mysql/conf.d
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=homestead
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret
      ports:
        - "${MYSQL_PORT}:3306"
